using System.Numerics;

namespace Lol.Net.Objects.Models.GameClients.Replays
{
    public record DecimalColor(decimal a, decimal b, decimal g, decimal r);
    public record RenderProperty
    (
        bool banners,
        bool cameraAttached,
        double cameraLookSpeed,
        string cameraMode,
        double cameraMoveSpeed,
        Vector3 cameraPosition,
        Vector3 cameraRotation,
        bool characters,
        DecimalColor depthFogColor,
        bool depthFogEnabled,
        double depthFogEnd,
        double depthFogIntensity,
        double depthFogStart,
        double depthOfFieldCircle,
        bool depthOfFieldDebug,
        bool depthOfFieldEnabled,
        double depthOfFieldFar,
        double depthOfFieldMid,
        double depthOfFieldNear,
        double depthOfFieldWidth,
        bool environment,
        double farClip,
        double fieldOfView,
        bool floatingText,
        bool fogOfWar,
        bool healthBarChampions,
        bool healthBarMinions,
        bool healthBarPets,
        bool healthBarStructures,
        bool healthBarWards,
        DecimalColor heightFogColor,
        bool heightFogEnabled,
        double heightFogEnd,
        double heightFogIntensity,
        double heightFogStart,
        bool interfaceAll,
        bool interfaceAnnounce,
        bool interfaceChat,
        bool interfaceFrames,
        bool interfaceKillCallouts,
        bool interfaceMinimap,
        bool interfaceNeutralTimers,
        object interfaceQuests,
        bool interfaceReplay,
        bool interfaceScore,
        bool interfaceScoreboard,
        bool interfaceTarget,
        bool interfaceTimeline,
        double navGridOffset,
        double nearClip,
        bool outlineHover,
        bool outlineSelect,
        bool particles,
        string selectionName,
        Vector3 selectionOffset,
        double skyboxOffset,
        string skyboxPath,
        double skyboxRadius,
        double skyboxRotation,
        Vector3 sunDirection
    );
}
